import type { ObjectType, StudioObject } from "./types";

export const objectPresets: Record<
  ObjectType,
  Omit<StudioObject, "id" | "x" | "y">
> = {
  sticky: {
    type: "sticky",
    title: "Sticky Note",
    content: "Write a quick idea, question, observation, or reminder.",
    width: 260,
    height: 190,
    color: "#fff7c2",
    icon: "📝",
    status: "Draft",
    createdIn: "shared",
    posterSection: "Supporting Notes",
    presentationSection: "Optional Notes",
    aiHint:
      "Check whether this note should become a stronger policy object such as evidence, problem statement, risk, or action item.",
    exportToPoster: false,
    exportToPresentation: false,
    tags: ["note", "idea", "workspace"],
    locked: false,
  },

  problem: {
    type: "problem",
    title: "Problem Statement",
    content:
      "The problem is [what] affecting [who] in [where/when] because [why], leading to [impact].",
    width: 340,
    height: 210,
    color: "#ffd6d6",
    icon: "🔍",
    status: "Draft",
    createdIn: "problem",
    posterSection: "Problem & Context",
    presentationSection: "Problem & Evidence",
    aiHint:
      "Check whether the problem statement clearly identifies what is happening, who is affected, where or when it occurs, why it matters, and what impact it creates.",
    exportToPoster: true,
    exportToPresentation: true,
    tags: ["problem", "context", "framing"],
    locked: false,
  },

  hmw: {
    type: "hmw",
    title: "How Might We Question",
    content:
      "How might we help [user/group] achieve [desired outcome] despite [barrier or constraint]?",
    width: 340,
    height: 180,
    color: "#fde68a",
    icon: "❓",
    status: "Draft",
    createdIn: "problem",
    posterSection: "Problem & Context",
    presentationSection: "Problem & Evidence",
    aiHint:
      "Check whether the HMW question is specific, action-oriented, human-centered, and not already jumping to a fixed solution.",
    exportToPoster: true,
    exportToPresentation: true,
    tags: ["hmw", "design question", "problem framing"],
    locked: false,
  },

  evidence: {
    type: "evidence",
    title: "Evidence Card",
    content:
      "Add evidence from literature, reports, datasets, field observations, interviews, or policy documents. Include the source.",
    width: 330,
    height: 200,
    color: "#dbeafe",
    icon: "📚",
    status: "Draft",
    createdIn: "problem",
    posterSection: "Evidence",
    presentationSection: "Problem & Evidence",
    aiHint:
      "Check whether the evidence is relevant, credible, recent enough, and clearly linked to the problem statement.",
    exportToPoster: true,
    exportToPresentation: true,
    tags: ["evidence", "literature", "data"],
    locked: false,
  },

  statistic: {
    type: "statistic",
    title: "Statistic Card",
    content:
      "Add one key statistic. Include number, population, year, location, and source.",
    width: 290,
    height: 170,
    color: "#dbeafe",
    icon: "📊",
    status: "Draft",
    createdIn: "problem",
    posterSection: "Evidence",
    presentationSection: "Problem & Evidence",
    aiHint:
      "Check whether the statistic includes a denominator, population, timeframe, source, and clear interpretation.",
    exportToPoster: true,
    exportToPresentation: true,
    tags: ["statistic", "data", "evidence"],
    locked: false,
  },

  source: {
    type: "source",
    title: "Source Card",
    content:
      "Add citation details: author/organization, year, title, publication/report, and link if available.",
    width: 300,
    height: 170,
    color: "#e0f2fe",
    icon: "🔖",
    status: "Draft",
    createdIn: "problem",
    posterSection: "References",
    presentationSection: "Backup Evidence",
    aiHint:
      "Check whether the source is credible, properly cited, and directly supports a claim used in the project.",
    exportToPoster: true,
    exportToPresentation: false,
    tags: ["source", "citation", "reference"],
    locked: false,
  },
  persona: {
    type: "persona",
    title: "Persona Card",
    content:
      "Describe the affected user: background, needs, barriers, goals, pain points, and context.",
    width: 320,
    height: 260,
    color: "#fef3c7",
    icon: "👤",
    status: "Draft",
    createdIn: "problem",
    posterSection: "Persona / Beneficiaries",
    presentationSection: "Problem & Evidence",
    aiHint:
      "Check whether this persona is realistic, specific, and clearly connected to the policy problem.",
    exportToPoster: true,
    exportToPresentation: true,
    tags: ["persona", "user", "beneficiary"],
    locked: false,
  },

  journey: {
    type: "journey",
    title: "Journey Map",
    content:
      "Map the user experience: before, during, and after interaction with the service or policy problem.",
    width: 430,
    height: 250,
    color: "#fef9c3",
    icon: "🛤️",
    status: "Draft",
    createdIn: "problem",
    posterSection: "User Journey",
    presentationSection: "Problem & Evidence",
    aiHint:
      "Check whether the journey map identifies key pain points, barriers, and opportunities for intervention.",
    exportToPoster: true,
    exportToPresentation: true,
    tags: ["journey", "user experience", "barriers"],
    locked: false,
  },

  fiveWhys: {
    type: "fiveWhys",
    title: "Five Whys",
    content:
      "Why 1 → Why 2 → Why 3 → Why 4 → Why 5. Use this to go deeper than the visible symptom.",
    width: 330,
    height: 230,
    color: "#e9d5ff",
    icon: "5️⃣",
    status: "Draft",
    createdIn: "problem",
    posterSection: "Root Causes",
    presentationSection: "Problem & Evidence",
    aiHint:
      "Check whether the analysis reaches an underlying cause rather than repeating the same surface-level issue.",
    exportToPoster: true,
    exportToPresentation: false,
    tags: ["five whys", "root cause", "analysis"],
    locked: false,
  },

  rootCause: {
    type: "rootCause",
    title: "Root Cause Card",
    content:
      "Identify one deeper cause of the problem. Explain how it contributes to the issue.",
    width: 310,
    height: 190,
    color: "#e9d5ff",
    icon: "🌱",
    status: "Draft",
    createdIn: "problem",
    posterSection: "Root Causes",
    presentationSection: "Problem & Evidence",
    aiHint:
      "Check whether this cause is supported by evidence and linked logically to the problem.",
    exportToPoster: true,
    exportToPresentation: true,
    tags: ["root cause", "analysis", "drivers"],
    locked: false,
  },

  problemTree: {
    type: "problemTree",
    title: "Problem Tree",
    content:
      "Causes → Core Problem → Effects. Use this to organize the problem structure visually.",
    width: 430,
    height: 270,
    color: "#ede9fe",
    icon: "🌳",
    status: "Draft",
    createdIn: "problem",
    posterSection: "Root Causes",
    presentationSection: "Problem & Evidence",
    aiHint:
      "Check whether causes, core problem, and effects are clearly separated and not mixed together.",
    exportToPoster: true,
    exportToPresentation: true,
    tags: ["problem tree", "causes", "effects"],
    locked: false,
  },
  stakeholder: {
    type: "stakeholder",
    title: "Stakeholder Card",
    content:
      "Identify one stakeholder. Add their role, interest, influence, power, and engagement need.",
    width: 320,
    height: 200,
    color: "#dcfce7",
    icon: "🤝",
    status: "Draft",
    createdIn: "process",
    posterSection: "Stakeholders & System",
    presentationSection: "Stakeholders & Process",
    aiHint:
      "Check whether the stakeholder role, power, interest, and engagement need are clearly explained.",
    exportToPoster: true,
    exportToPresentation: true,
    tags: ["stakeholder", "power", "interest"],
    locked: false,
  },

  systemNode: {
    type: "systemNode",
    title: "System Node",
    content:
      "Add one actor, institution, process, policy lever, barrier, or system factor.",
    width: 280,
    height: 170,
    color: "#dcfce7",
    icon: "🧩",
    status: "Draft",
    createdIn: "process",
    posterSection: "Stakeholders & System",
    presentationSection: "Stakeholders & Process",
    aiHint:
      "Check whether this system node is connected to other actors, processes, or constraints.",
    exportToPoster: true,
    exportToPresentation: true,
    tags: ["system", "actor", "relationship"],
    locked: false,
  },

  idea: {
    type: "idea",
    title: "Solution Idea",
    content:
      "Describe one possible policy option or intervention. Include what it changes and who benefits.",
    width: 320,
    height: 190,
    color: "#ccfbf1",
    icon: "💡",
    status: "Draft",
    createdIn: "solution",
    posterSection: "Proposed Solution",
    presentationSection: "Proposed Solution",
    aiHint:
      "Check whether the idea addresses the root cause and is feasible within the policy context.",
    exportToPoster: true,
    exportToPresentation: true,
    tags: ["solution", "intervention", "policy option"],
    locked: false,
  },

  theoryOfChange: {
    type: "theoryOfChange",
    title: "Theory of Change",
    content:
      "Inputs → Activities → Outputs → Outcomes → Impact. Explain the logic of change.",
    width: 460,
    height: 270,
    color: "#ccfbf1",
    icon: "🔄",
    status: "Draft",
    createdIn: "solution",
    posterSection: "Theory of Change",
    presentationSection: "Proposed Solution",
    aiHint:
      "Check whether the pathway from inputs to impact is logical, realistic, and supported by assumptions.",
    exportToPoster: true,
    exportToPresentation: true,
    tags: ["theory of change", "logic model", "impact"],
    locked: false,
  },
  timeline: {
    type: "timeline",
    title: "Implementation Timeline",
    content:
      "Add key implementation phases, milestones, responsible actors, and expected completion dates.",
    width: 450,
    height: 240,
    color: "#FEF3C7",
    icon: "🗓️",
    status: "Draft",
    createdIn: "implementation",
    posterSection: "Implementation Overview",
    presentationSection: "Implementation Plan",
    aiHint:
      "Check whether the timeline is realistic, sequential, and includes measurable milestones.",
    exportToPoster: true,
    exportToPresentation: true,
    tags: ["timeline", "implementation", "milestones"],
    locked: false,
  },

  budget: {
    type: "budget",
    title: "Budget Card",
    content:
      "Estimate implementation costs, funding sources, and key assumptions.",
    width: 330,
    height: 210,
    color: "#DCFCE7",
    icon: "💰",
    status: "Draft",
    createdIn: "implementation",
    posterSection: "Resources & Budget",
    presentationSection: "Implementation Plan",
    aiHint:
      "Check whether budget assumptions are realistic and linked to implementation activities.",
    exportToPoster: true,
    exportToPresentation: true,
    tags: ["budget", "cost", "finance"],
    locked: false,
  },

  risk: {
    type: "risk",
    title: "Risk Card",
    content:
      "Describe one implementation risk and explain its possible impact.",
    width: 320,
    height: 180,
    color: "#FEE2E2",
    icon: "⚠️",
    status: "Draft",
    createdIn: "implementation",
    posterSection: "Risks",
    presentationSection: "Risks",
    aiHint:
      "Check whether the risk is specific, realistic, and directly related to implementation.",
    exportToPoster: true,
    exportToPresentation: true,
    tags: ["risk", "implementation"],
    locked: false,
  },

  mitigation: {
    type: "mitigation",
    title: "Mitigation Strategy",
    content:
      "Describe how the identified implementation risk can be prevented or reduced.",
    width: 330,
    height: 190,
    color: "#FFEDD5",
    icon: "🛡️",
    status: "Draft",
    createdIn: "implementation",
    posterSection: "Risks",
    presentationSection: "Risks",
    aiHint:
      "Check whether the mitigation strategy is feasible and proportional to the identified risk.",
    exportToPoster: true,
    exportToPresentation: true,
    tags: ["mitigation", "risk response"],
    locked: false,
  },

  indicator: {
    type: "indicator",
    title: "Monitoring Indicator",
    content:
      "Define an indicator, baseline, target, data source, and reporting frequency.",
    width: 340,
    height: 200,
    color: "#DBEAFE",
    icon: "📏",
    status: "Draft",
    createdIn: "implementation",
    posterSection: "Monitoring & Evaluation",
    presentationSection: "Evaluation",
    aiHint:
      "Check whether the indicator is SMART and linked to the project objectives.",
    exportToPoster: true,
    exportToPresentation: true,
    tags: ["indicator", "evaluation", "monitoring"],
    locked: false,
  },

  chart: {
    type: "chart",
    title: "Chart / Graph",
    content:
      "AI-generated or manually created chart summarizing evidence or implementation data.",
    width: 430,
    height: 280,
    color: "#E0F2FE",
    icon: "📈",
    status: "Draft",
    createdIn: "shared",
    posterSection: "Visual Evidence",
    presentationSection: "Visual Evidence",
    aiHint:
      "Recommend the most appropriate visualization (bar, line, pie, flowchart, Sankey, timeline, etc.) based on the available data.",
    exportToPoster: true,
    exportToPresentation: true,
    tags: ["graph", "chart", "visualization"],
    locked: false,
  },

  aiVisual: {
    type: "aiVisual",
    title: "AI Visual",
    content:
      "Generate a visual using an AI prompt. Examples: infographic, stakeholder map, journey map, system map, implementation flow.",
    width: 450,
    height: 290,
    color: "#CCFBF1",
    icon: "✨",
    status: "Draft",
    createdIn: "shared",
    posterSection: "Visuals",
    presentationSection: "Visuals",
    aiHint:
      "Recommend the best visual representation based on the student's current work.",
    exportToPoster: true,
    exportToPresentation: true,
    tags: ["AI", "visual", "diagram"],
    locked: false,
  },

  icon: {
    type: "icon",
    title: "Icon",
    content: "Decorative icon used inside the workspace.",
    width: 80,
    height: 80,
    color: "#FFFFFF",
    icon: "⭐",
    status: "Draft",
    createdIn: "shared",
    posterSection: "",
    presentationSection: "",
    aiHint: "",
    exportToPoster: false,
    exportToPresentation: false,
    tags: ["icon"],
    locked: false,
  },
};
