create table if not exists public.professor_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  project_key text not null,
  studio_id text not null,
  studio_name text not null,
  group_number text not null,
  course_name text not null,
  policy_issue text not null,
  submitted_by_name text not null,
  submitted_by_email text not null,
  professor_name text not null,
  professor_email text not null,
  question text not null,
  status text not null default 'Submitted',
  review_token text,
  review_notes text,
  reviewed_at timestamp with time zone
);

alter table public.professor_feedback enable row level security;

create policy if not exists "Allow inserts for authenticated users"
  on public.professor_feedback
  for insert
  to authenticated
  with check (true);

create policy if not exists "Allow select for authenticated users"
  on public.professor_feedback
  for select
  to authenticated
  using (true);
